# Generated by Django 5.0 on 2023-12-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Watch')),
                ('name', models.CharField(max_length=20)),
                ('price', models.ImageField(upload_to='')),
                ('aksiya_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'watch',
                'verbose_name_plural': 'watchs',
            },
        ),
    ]
