# Generated by Django 5.0 on 2023-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_watchmodel_create_at_watchmodel_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
