# Generated by Django 5.0 on 2023-12-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_watchmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmodel',
            name='image',
            field=models.ImageField(upload_to='watch/'),
        ),
    ]
