# Generated by Django 5.0 on 2023-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_watchmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmodel',
            name='category',
            field=models.ManyToManyField(to='pages.category'),
        ),
    ]
